# Generated by Django 4.2.6 on 2023-11-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_com_web', '0002_article_content_article_imgthumb_article_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navigate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('link', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='imgThumb',
            field=models.ImageField(blank=True, null=True, upload_to='media_img'),
        ),
        migrations.AlterField(
            model_name='article',
            name='year',
            field=models.PositiveSmallIntegerField(default=2020),
        ),
    ]
