# Generated by Django 4.2.6 on 2023-11-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_com_web', '0003_navigate_alter_article_imgthumb_alter_article_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Navigate',
        ),
        migrations.AlterField(
            model_name='article',
            name='imgThumb',
            field=models.ImageField(blank=True, null=True, upload_to='media.ing'),
        ),
        migrations.AlterField(
            model_name='article',
            name='year',
            field=models.PositiveSmallIntegerField(default=2023),
        ),
    ]
